import { DEFAULT_ACTION_COSTS } from '@/lib/exception-room/config';
import { evidence } from '@/lib/exception-room/content/helpers';
import type { ExceptionCase } from '@/lib/exception-room/types';

export const FINAL_CAMPAIGN_CASES = [
  {
    id: 'conflict-needs-specialist',
    archetype: 'conflicting-authoritative-sources',
    summary: 'Two current authoritative sources conflict, and the reviewer lacks a rule for choosing between them.',
    recommendation: 'Use the source with the latest upload timestamp.',
    confidenceBand: 'high',
    consequence: 'critical',
    reversibility: 'difficult',
    routeReasons: ['conflicting-evidence'],
    evidence: [
      evidence('specialist-source-a', 'Authoritative source A', 'supports', 'Source A supports the recommendation and has the latest upload.', 1),
      evidence('specialist-source-b', 'Authoritative source B', 'conflicts', 'Source B is equally current and records a different approved value.', 1),
      evidence('specialist-policy', 'Conflict policy', 'missing', 'No rule establishes which source controls this conflict.', 1, 'policy'),
    ],
    shift: 3,
    dueOffsetTicks: 2,
    carryover: true,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'escalate',
    acceptableActions: [],
    outcomeByAction: { approve: 'unsafe', correct: 'unsafe', escalate: 'preferred' },
    escalationOptions: [{ id: 'record-specialist', label: 'Send both sources for resolution', destinationRole: 'Record specialist' }],
    detailOutcomeById: { escalate: { 'record-specialist': 'preferred' } },
    requiredEvidenceIds: ['specialist-source-a', 'specialist-source-b', 'specialist-policy'],
    rationale: 'Recency cannot resolve two equally authoritative records. A specialist must establish the controlling source before completion.',
    mishandlingConsequence: 'The workflow commits a critical value without a defensible source-of-truth decision.',
    learningDestination: 'policy',
  },
  {
    id: 'missing-citation-correctable',
    archetype: 'missing-model-citation',
    summary: 'The model omitted its citation, but the reviewer can verify and repair the value from the current record.',
    recommendation: 'Accept the uncited value as generated.',
    confidenceBand: 'medium',
    consequence: 'high',
    reversibility: 'difficult',
    routeReasons: ['missing-evidence'],
    evidence: [
      evidence('citation-gap', 'Model citation', 'missing', 'The recommendation contains no source reference.', 1, 'history'),
      evidence('current-value', 'Current service record', 'conflicts', 'The authoritative record provides a different current value.', 1),
    ],
    shift: 3,
    dueOffsetTicks: 2,
    carryover: true,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'correct',
    acceptableActions: [],
    outcomeByAction: { approve: 'unsafe', correct: 'preferred', escalate: 'unnecessary' },
    correctionOptions: [{ id: 'use-current-value', label: 'Use the current record value' }],
    escalationOptions: [{ id: 'record-specialist', label: 'Send for redundant source review', destinationRole: 'Record specialist' }],
    detailOutcomeById: {
      correct: { 'use-current-value': 'preferred' },
      escalate: { 'record-specialist': 'unnecessary' },
    },
    requiredEvidenceIds: ['citation-gap', 'current-value'],
    rationale: 'The model citation is missing, but the current authoritative record supplies enough evidence for a bounded correction.',
    mishandlingConsequence: 'An unsupported stale value enters a difficult-to-reverse downstream workflow.',
    learningDestination: 'workflow',
    contentNotes: ['This case becomes more urgent as it ages.'],
  },
  {
    id: 'repeated-date-drift-two',
    archetype: 'recurring-date-drift',
    summary: 'The same one-day mapping defect appears again after an earlier correction.',
    recommendation: 'Save the shifted date and continue processing.',
    confidenceBand: 'medium',
    consequence: 'high',
    reversibility: 'moderate',
    routeReasons: ['repeat-correction'],
    evidence: [
      evidence('drift-source-two', 'Submitted source', 'conflicts', 'The source date is one day earlier than the recommendation.', 1, 'submitted-document'),
      evidence('drift-history-two', 'Correction history', 'context', 'The same defect now appears across several recent cases.', 1, 'history'),
      evidence('drift-rule-state', 'Mapping rule status', 'context', 'The mapping rule has not been repaired after earlier corrections.', 1, 'policy'),
    ],
    shift: 3,
    dueOffsetTicks: 2,
    carryover: true,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'escalate',
    acceptableActions: ['correct'],
    outcomeByAction: { approve: 'unsafe', correct: 'acceptable', escalate: 'preferred' },
    correctionOptions: [{ id: 'source-date-repeat', label: 'Correct this case only' }],
    escalationOptions: [{ id: 'workflow-owner', label: 'Escalate the recurring defect', destinationRole: 'Workflow owner' }],
    detailOutcomeById: {
      correct: { 'source-date-repeat': 'acceptable' },
      escalate: { 'workflow-owner': 'preferred' },
    },
    requiredEvidenceIds: ['drift-source-two', 'drift-history-two', 'drift-rule-state'],
    rationale: 'Correcting this case is defensible, but the repeated defect now warrants a workflow-owner handoff so the source rule can be fixed.',
    mishandlingConsequence: 'Another shifted date enters the service and the recurring defect remains invisible.',
    learningDestination: 'workflow',
  },
] as const satisfies readonly ExceptionCase[];
