import { DEFAULT_ACTION_COSTS } from '@/lib/exception-room/config';
import { FINAL_CAMPAIGN_CASES } from '@/lib/exception-room/content/campaign-final';
import { evidence } from '@/lib/exception-room/content/helpers';
import type { ExceptionCase } from '@/lib/exception-room/types';

export const CAMPAIGN_CASES = [
  {
    id: 'effective-date-conflict',
    archetype: 'stale-authoritative-record',
    summary: 'A high-confidence recommendation uses an older effective date than the current service record.',
    recommendation: 'Apply the older effective date and release the downstream update.',
    confidenceBand: 'high',
    consequence: 'critical',
    reversibility: 'difficult',
    routeReasons: ['conflicting-evidence'],
    evidence: [
      evidence('current-record', 'Current service record', 'conflicts', 'The active record shows a newer effective date.', 1),
      evidence('submitted-copy', 'Submitted reference copy', 'supports', 'The submitted copy contains the older date used by the recommendation.', 4, 'submitted-document'),
    ],
    shift: 1,
    dueOffsetTicks: 2,
    carryover: true,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'correct',
    acceptableActions: ['escalate'],
    outcomeByAction: { approve: 'unsafe', correct: 'preferred', escalate: 'acceptable' },
    correctionOptions: [
      { id: 'use-current-date', label: 'Use the current service date' },
      { id: 'keep-submitted-date', label: 'Keep the submitted date' },
    ],
    escalationOptions: [{ id: 'record-specialist', label: 'Send for source resolution', destinationRole: 'Record specialist' }],
    detailOutcomeById: {
      correct: { 'use-current-date': 'preferred', 'keep-submitted-date': 'unsafe' },
      escalate: { 'record-specialist': 'acceptable' },
    },
    requiredEvidenceIds: ['current-record', 'submitted-copy'],
    rationale: 'The current service record is newer and authoritative. Correcting the date prevents a difficult downstream reversal; escalation is defensible but slower.',
    mishandlingConsequence: 'The older date triggers an incorrect downstream update that is difficult to reverse.',
    learningDestination: 'evaluation-set',
  },
  {
    id: 'unfamiliar-clean-layout',
    archetype: 'unfamiliar-clean-input',
    summary: 'A low-confidence recommendation comes from an unfamiliar layout, but both source values agree.',
    recommendation: 'Accept the extracted category and reference value.',
    confidenceBand: 'low',
    consequence: 'low',
    reversibility: 'easy',
    routeReasons: ['low-confidence'],
    evidence: [
      evidence('layout-source', 'Submitted source', 'supports', 'The category and value match the recommendation.', 1, 'submitted-document'),
      evidence('record-match', 'Service record', 'supports', 'The current record independently confirms both fields.', 1),
    ],
    shift: 1,
    dueOffsetTicks: 3,
    carryover: false,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'approve',
    acceptableActions: [],
    outcomeByAction: { approve: 'preferred', correct: 'unnecessary', escalate: 'unnecessary' },
    escalationOptions: [{ id: 'quality-reviewer', label: 'Send for additional quality review', destinationRole: 'Quality reviewer' }],
    detailOutcomeById: { escalate: { 'quality-reviewer': 'unnecessary' } },
    requiredEvidenceIds: ['layout-source', 'record-match'],
    rationale: 'The layout is unfamiliar, but the recommendation is supported by two matching sources and the action is easy to reverse.',
    mishandlingConsequence: 'Extra review delays a low-risk case without improving the result.',
    learningDestination: 'evaluation-set',
  },
  {
    id: 'missing-approval-evidence',
    archetype: 'missing-required-evidence',
    summary: 'A recommendation would start a high-consequence action, but the required approval record is absent.',
    recommendation: 'Proceed with the action using the available submitted record.',
    confidenceBand: 'medium',
    consequence: 'high',
    reversibility: 'difficult',
    routeReasons: ['missing-evidence'],
    evidence: [
      evidence('submitted-request', 'Submitted request', 'supports', 'The request contains the expected values.', 1, 'submitted-document'),
      evidence('approval-record', 'Required approval record', 'missing', 'No current approval record is attached or available.', 1, 'policy'),
    ],
    shift: 1,
    dueOffsetTicks: 2,
    carryover: true,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'escalate',
    acceptableActions: [],
    outcomeByAction: { approve: 'unsafe', correct: 'unsafe', escalate: 'preferred' },
    escalationOptions: [
      { id: 'approval-owner', label: 'Request the missing approval', destinationRole: 'Approval owner' },
      { id: 'quality-team', label: 'Send for general quality review', destinationRole: 'Quality team' },
    ],
    detailOutcomeById: { escalate: { 'approval-owner': 'preferred', 'quality-team': 'unnecessary' } },
    requiredEvidenceIds: ['submitted-request', 'approval-record'],
    rationale: 'The reviewer lacks the required approval evidence and cannot repair that authority gap. The approval owner must complete the handoff.',
    mishandlingConsequence: 'The system starts a high-consequence action without the required authorization.',
    learningDestination: 'workflow',
  },
  {
    id: 'sampled-clean-match',
    archetype: 'clean-quality-sample',
    summary: 'A high-confidence quality sample matches the current record and contains no conflicting evidence.',
    recommendation: 'Accept the category and continue the routine workflow.',
    confidenceBand: 'high',
    consequence: 'medium',
    reversibility: 'moderate',
    routeReasons: ['random-quality-sample'],
    evidence: [
      evidence('sample-source', 'Submitted sample', 'supports', 'The source clearly supports the recommended category.', 1, 'submitted-document'),
      evidence('sample-record', 'Current service record', 'supports', 'The service record matches the source and recommendation.', 1),
    ],
    shift: 2,
    dueOffsetTicks: 3,
    carryover: false,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'approve',
    acceptableActions: [],
    outcomeByAction: { approve: 'preferred', correct: 'unnecessary', escalate: 'unnecessary' },
    escalationOptions: [{ id: 'quality-reviewer', label: 'Send for additional quality review', destinationRole: 'Quality reviewer' }],
    detailOutcomeById: { escalate: { 'quality-reviewer': 'unnecessary' } },
    requiredEvidenceIds: ['sample-source', 'sample-record'],
    rationale: 'The sample is supported by the current record. Approval completes the review without adding avoidable work.',
    mishandlingConsequence: 'Unnecessary correction or escalation consumes review capacity and delays other cases.',
    learningDestination: 'none',
  },
  {
    id: 'low-confidence-unit-error',
    archetype: 'bounded-extraction-error',
    summary: 'A low-confidence recommendation uses the right value with the wrong unit.',
    recommendation: 'Record the value as 48 hours.',
    confidenceBand: 'low',
    consequence: 'low',
    reversibility: 'easy',
    routeReasons: ['low-confidence'],
    evidence: [
      evidence('unit-source', 'Submitted source', 'conflicts', 'The source states 48 minutes, not 48 hours.', 1, 'submitted-document'),
      evidence('unit-history', 'Recent similar record', 'context', 'Similar entries use minutes for this field.', 3, 'history'),
    ],
    shift: 2,
    dueOffsetTicks: 3,
    carryover: false,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'correct',
    acceptableActions: ['escalate'],
    outcomeByAction: { approve: 'unsafe', correct: 'preferred', escalate: 'acceptable' },
    correctionOptions: [
      { id: 'minutes', label: 'Change the unit to minutes' },
      { id: 'days', label: 'Change the unit to days' },
    ],
    escalationOptions: [{ id: 'data-quality-specialist', label: 'Send for unit verification', destinationRole: 'Data quality specialist' }],
    detailOutcomeById: {
      correct: { minutes: 'preferred', days: 'unsafe' },
      escalate: { 'data-quality-specialist': 'acceptable' },
    },
    requiredEvidenceIds: ['unit-source'],
    rationale: 'The source provides a bounded correction. Escalation is safe but spends more capacity than the correction requires.',
    mishandlingConsequence: 'The wrong unit produces an incorrect service interval that must be reversed later.',
    learningDestination: 'rule',
  },
  {
    id: 'repeated-date-drift-one',
    archetype: 'recurring-date-drift',
    summary: 'A repeated mapping defect shifted a supported date by one day.',
    recommendation: 'Save the shifted date shown by the recommendation.',
    confidenceBand: 'medium',
    consequence: 'high',
    reversibility: 'moderate',
    routeReasons: ['repeat-correction'],
    evidence: [
      evidence('drift-source-one', 'Submitted source', 'conflicts', 'The source date is one day earlier than the recommendation.', 1, 'submitted-document'),
      evidence('drift-history-one', 'Correction history', 'context', 'Three recent cases show the same one-day shift.', 2, 'history'),
    ],
    shift: 2,
    dueOffsetTicks: 2,
    carryover: true,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'correct',
    acceptableActions: [],
    outcomeByAction: { approve: 'unsafe', correct: 'preferred', escalate: 'unnecessary' },
    correctionOptions: [{ id: 'source-date', label: 'Use the date shown in the source' }],
    escalationOptions: [{ id: 'workflow-owner', label: 'Send the individual case to the workflow owner', destinationRole: 'Workflow owner' }],
    detailOutcomeById: {
      correct: { 'source-date': 'preferred' },
      escalate: { 'workflow-owner': 'unnecessary' },
    },
    requiredEvidenceIds: ['drift-source-one', 'drift-history-one'],
    rationale: 'The source resolves this case, so the reviewer can correct it now. The repeated pattern should also create a product defect signal.',
    mishandlingConsequence: 'The shifted date creates a preventable service error and another later correction.',
    learningDestination: 'rule',
  },
  {
    id: 'boundary-needs-owner',
    archetype: 'authority-boundary',
    summary: 'The recommendation sits outside reviewer authority and requires a named policy owner.',
    recommendation: 'Approve the exception under the standard operating rule.',
    confidenceBand: 'medium',
    consequence: 'medium',
    reversibility: 'difficult',
    routeReasons: ['policy-boundary'],
    evidence: [
      evidence('boundary-policy', 'Current policy', 'conflicts', 'The policy reserves this exception for the policy owner.', 1, 'policy'),
      evidence('boundary-history', 'Prior decision history', 'context', 'Earlier exceptions were routed to the same owner.', 3, 'history'),
    ],
    shift: 2,
    dueOffsetTicks: 3,
    carryover: true,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'escalate',
    acceptableActions: [],
    outcomeByAction: { approve: 'unsafe', correct: 'unsafe', escalate: 'preferred' },
    escalationOptions: [{ id: 'policy-owner', label: 'Send to the policy owner', destinationRole: 'Policy owner' }],
    detailOutcomeById: { escalate: { 'policy-owner': 'preferred' } },
    requiredEvidenceIds: ['boundary-policy'],
    rationale: 'The evidence is clear, but the reviewer lacks authority. Escalation reaches the named owner without pretending the queue can grant authority.',
    mishandlingConsequence: 'The reviewer applies an exception they are not authorized to approve.',
    learningDestination: 'policy',
  },
  {
    id: 'boundary-cleared-by-policy',
    archetype: 'authority-confirmed',
    summary: 'A policy-boundary route is already covered by a current rule that grants reviewer authority.',
    recommendation: 'Approve the routine exception under the current rule.',
    confidenceBand: 'medium',
    consequence: 'medium',
    reversibility: 'difficult',
    routeReasons: ['policy-boundary'],
    evidence: [
      evidence('authority-policy', 'Current policy', 'supports', 'The current rule explicitly grants reviewer authority for this case.', 1, 'policy'),
      evidence('authority-record', 'Service record', 'supports', 'The record meets every condition in the current rule.', 1),
    ],
    shift: 3,
    dueOffsetTicks: 3,
    carryover: true,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'approve',
    acceptableActions: [],
    outcomeByAction: { approve: 'preferred', correct: 'unnecessary', escalate: 'unnecessary' },
    escalationOptions: [{ id: 'policy-owner', label: 'Send for redundant policy review', destinationRole: 'Policy owner' }],
    detailOutcomeById: { escalate: { 'policy-owner': 'unnecessary' } },
    requiredEvidenceIds: ['authority-policy', 'authority-record'],
    rationale: 'The route reason invites inspection, but the current policy and record confirm that the reviewer can approve.',
    mishandlingConsequence: 'Unnecessary escalation creates avoidable owner workload and delays the service.',
    learningDestination: 'workflow',
  },
  {
    id: 'sampled-field-mismatch',
    archetype: 'sampled-extraction-error',
    summary: 'A high-confidence quality sample contains one field that conflicts with the source.',
    recommendation: 'Accept all extracted fields as shown.',
    confidenceBand: 'high',
    consequence: 'medium',
    reversibility: 'moderate',
    routeReasons: ['random-quality-sample'],
    evidence: [
      evidence('sample-mismatch-source', 'Submitted sample', 'conflicts', 'One reference field differs from the recommendation.', 1, 'submitted-document'),
      evidence('sample-mismatch-record', 'Current service record', 'supports', 'The current record confirms the value in the source.', 1),
    ],
    shift: 3,
    dueOffsetTicks: 3,
    carryover: false,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'correct',
    acceptableActions: [],
    outcomeByAction: { approve: 'unsafe', correct: 'preferred', escalate: 'unnecessary' },
    correctionOptions: [{ id: 'match-source', label: 'Replace the mismatched field' }],
    escalationOptions: [{ id: 'data-quality-specialist', label: 'Send for field verification', destinationRole: 'Data quality specialist' }],
    detailOutcomeById: {
      correct: { 'match-source': 'preferred' },
      escalate: { 'data-quality-specialist': 'unnecessary' },
    },
    requiredEvidenceIds: ['sample-mismatch-source', 'sample-mismatch-record'],
    rationale: 'The quality sample caught a bounded error. Correcting the single field is safe and less costly than escalation.',
    mishandlingConsequence: 'The mismatched field enters the service record and requires later rework.',
    learningDestination: 'evaluation-set',
  },
  ...FINAL_CAMPAIGN_CASES,
] as const satisfies readonly ExceptionCase[];
