import { DEFAULT_ACTION_COSTS } from '@/lib/exception-room/config';
import { evidence } from '@/lib/exception-room/content/helpers';
import type { ExceptionCase } from '@/lib/exception-room/types';

export const PRACTICE_CASES = [
  {
    id: 'practice-approve',
    archetype: 'practice-clean-match',
    summary: 'Two current sources support a low-risk recommendation.',
    recommendation: 'Accept the supported category.',
    confidenceBand: 'medium',
    consequence: 'low',
    reversibility: 'easy',
    routeReasons: ['random-quality-sample'],
    evidence: [
      evidence('practice-approve-source', 'Submitted source', 'supports', 'The source supports the category.', 1, 'submitted-document'),
      evidence('practice-approve-record', 'Current record', 'supports', 'The current record confirms the category.', 1),
    ],
    shift: 1,
    dueOffsetTicks: 3,
    carryover: false,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'approve',
    acceptableActions: [],
    outcomeByAction: { approve: 'preferred', correct: 'unnecessary', escalate: 'unnecessary' },
    escalationOptions: [{ id: 'practice-quality-reviewer', label: 'Send for additional quality review', destinationRole: 'Quality reviewer' }],
    detailOutcomeById: { escalate: { 'practice-quality-reviewer': 'unnecessary' } },
    requiredEvidenceIds: ['practice-approve-source', 'practice-approve-record'],
    rationale: 'The sources agree and the consequence is low, so approval is the capacity-aware choice.',
    mishandlingConsequence: 'Extra work delays another case without improving this result.',
    learningDestination: 'none',
  },
  {
    id: 'practice-correct',
    archetype: 'practice-bounded-error',
    summary: 'The recommendation contains one value that conflicts with the source.',
    recommendation: 'Record the value as 17.',
    confidenceBand: 'high',
    consequence: 'medium',
    reversibility: 'moderate',
    routeReasons: ['conflicting-evidence'],
    evidence: [
      evidence('practice-correct-source', 'Submitted source', 'conflicts', 'The source shows 71, not 17.', 1, 'submitted-document'),
      evidence('practice-correct-record', 'Current record', 'supports', 'The current record also shows 71.', 1),
    ],
    shift: 1,
    dueOffsetTicks: 3,
    carryover: false,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'correct',
    acceptableActions: [],
    outcomeByAction: { approve: 'unsafe', correct: 'preferred', escalate: 'unnecessary' },
    correctionOptions: [{ id: 'practice-use-71', label: 'Change the value to 71' }],
    escalationOptions: [{ id: 'practice-record-specialist', label: 'Send for redundant value review', destinationRole: 'Record specialist' }],
    detailOutcomeById: {
      correct: { 'practice-use-71': 'preferred' },
      escalate: { 'practice-record-specialist': 'unnecessary' },
    },
    requiredEvidenceIds: ['practice-correct-source', 'practice-correct-record'],
    rationale: 'The sources identify a bounded error that the reviewer can repair directly.',
    mishandlingConsequence: 'The wrong value enters the service record.',
    learningDestination: 'evaluation-set',
  },
  {
    id: 'practice-escalate',
    archetype: 'practice-authority-gap',
    summary: 'The evidence is complete, but the reviewer lacks authority for this exception.',
    recommendation: 'Approve the exception under the standard rule.',
    confidenceBand: 'high',
    consequence: 'high',
    reversibility: 'difficult',
    routeReasons: ['policy-boundary'],
    evidence: [
      evidence('practice-policy', 'Current policy', 'conflicts', 'Only the policy owner may approve this exception.', 1, 'policy'),
      evidence('practice-record', 'Current record', 'context', 'The record confirms that the exception applies.', 1),
    ],
    shift: 1,
    dueOffsetTicks: 3,
    carryover: false,
    actionCosts: DEFAULT_ACTION_COSTS,
    preferredAction: 'escalate',
    acceptableActions: [],
    outcomeByAction: { approve: 'unsafe', correct: 'unsafe', escalate: 'preferred' },
    escalationOptions: [{ id: 'practice-policy-owner', label: 'Send to the policy owner', destinationRole: 'Policy owner' }],
    detailOutcomeById: { escalate: { 'practice-policy-owner': 'preferred' } },
    requiredEvidenceIds: ['practice-policy', 'practice-record'],
    rationale: 'Evidence does not replace authority. The named policy owner must make the decision.',
    mishandlingConsequence: 'The reviewer applies an exception they are not authorized to approve.',
    learningDestination: 'policy',
  },
] as const satisfies readonly ExceptionCase[];
