import type { Card } from '@/lib/shipit/types';

export const ARCS = ['incident', 'big-customer', 'burnout', 'launch-gamble'] as const;

export const PRODUCTS: readonly string[] = [
  'Plumage, a B2B invoicing tool',
  'Krill, a team chat app for shipping crews',
  'Lantern, a nightlife discovery app',
  'Stackline, an internal-tools platform',
  'Pantry, a meal-kit subscription service',
  'Copperwire, a fintech API for landlords',
];

export const DECK: Card[] = [
  // ============================== core dilemmas ==============================
  {
    id: 'roadmap-vs-refactor',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'The checkout service is held together with feature flags and prayer. I need three weeks to rebuild it — or we keep shipping and I keep patching.',
    left: { label: 'Take the three weeks', effects: { tech: 16, business: -8, users: -4 } },
    right: { label: 'Keep shipping, keep patching', effects: { business: 8, tech: -10 } },
  },
  {
    id: 'enterprise-checkbox',
    speaker: 'Jonas, Sales',
    avatar: '🤵',
    text: 'I can close a six-figure deal today if we promise SSO by end of quarter. Legal already drafted the contract. It is one checkbox, how hard can it be?',
    left: { label: 'Promise SSO', effects: { business: 12, team: -8, tech: -6 }, setFlags: ['promised-sso'] },
    right: { label: 'Lose the deal', effects: { business: -10, team: 4 } },
  },
  {
    id: 'dark-pattern-growth',
    speaker: 'Sam, Marketing',
    avatar: '📣',
    text: 'Growth found a trick: pre-checked "invite your contacts" during signup. Conversion on invites triples. The designers are calling it a dark pattern in Slack.',
    left: { label: 'Ship the pre-check', effects: { users: 12, business: 4, team: -8 } },
    right: { label: 'Keep invites opt-in', effects: { users: -4, team: 6 } },
  },
  {
    id: 'onboarding-friction',
    speaker: 'Dele, Design',
    avatar: '🎨',
    text: 'Signup asks eleven questions before anyone sees the product. I can cut it to two — but Sales says the other nine feed their lead scoring.',
    left: { label: 'Cut it to two questions', effects: { users: 10, business: -6 } },
    right: { label: 'Keep the lead form', effects: { business: 6, users: -6 } },
  },
  {
    id: 'conference-week',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'Half the team wants to attend LeadDev the week before the roadmap review. It would be great for morale and terrible for the demo.',
    left: { label: 'Send them', effects: { team: 14, business: -6 } },
    right: { label: 'Demo first, conference next year', effects: { team: -8, business: 6 } },
  },
  {
    id: 'price-increase',
    speaker: 'Jonas, Sales',
    avatar: '🤵',
    text: 'Finance modeled a 20% price increase. Existing customers grandfathered for six months. The forum will notice in about four minutes.',
    left: { label: 'Raise prices', effects: { business: 12, users: -10 } },
    right: { label: 'Hold pricing', effects: { users: 4, business: -6 } },
  },
  {
    id: 'stale-flags',
    speaker: 'Ana, Data',
    avatar: '📊',
    text: 'There are 43 stale feature flags in production. Two conflict with each other. Cleaning them up is a sprint of pure janitorial work.',
    left: { label: 'Spend the sprint cleaning', effects: { tech: 14, users: -4 } },
    right: { label: 'Flags are free, ship features', effects: { users: 6, tech: -8 } },
  },
  {
    id: 'exec-pet-feature',
    speaker: 'The CEO',
    avatar: '🧑‍💼',
    text: 'I sketched a "command center" dashboard on the flight back. Investors will love it. I want it in the next release. What do you mean, "discovery"?',
    left: { label: 'Build the command center', effects: { business: 8, users: -6, team: -6 } },
    right: { label: 'Push back with data', effects: { business: -10, team: 6 } },
  },
  {
    id: 'support-queue',
    speaker: 'Priya, Support',
    avatar: '🎧',
    text: 'The queue is three days deep and people are tweeting screenshots. Give me two engineers for a week and I can clear it and fix the top macro.',
    left: { label: 'Lend the engineers', effects: { users: 8, team: -6 } },
    right: { label: 'Keep them building', effects: { tech: 6, users: -8 } },
  },
  {
    id: 'a11y-audit',
    speaker: 'Dele, Design',
    avatar: '🎨',
    text: 'The accessibility audit came back: 61 issues, 9 blockers. Fixing them properly is two sprints. Or we fix the blockers and file the rest as "backlog".',
    left: { label: 'Fix it properly', effects: { users: 6, tech: 6, business: -6 } },
    right: { label: 'Blockers only', effects: { business: 4, users: -6 } },
  },
  {
    id: 'data-pipeline',
    speaker: 'Ana, Data',
    avatar: '📊',
    text: 'The events pipeline drops 12% of traffic on Tuesdays. Nobody knows why. Every metric you have quoted this quarter has been slightly wrong.',
    left: { label: 'Fund the pipeline rebuild', effects: { tech: 12, business: -6 } },
    right: { label: 'Ship features, guess metrics', effects: { business: 6, tech: -6, users: -4 } },
  },
  {
    id: 'competitor-launch',
    speaker: 'Sam, Marketing',
    avatar: '📣',
    text: 'Our biggest competitor just shipped our top three roadmap items in one release. TechCrunch called it "category-defining". Your move.',
    left: { label: 'Rush a counter-launch', effects: { users: 8, tech: -8, team: -6 } },
    right: { label: 'Stay the course', effects: { users: -6, business: -4, team: 4 } },
  },
  {
    id: 'intern-bot',
    speaker: 'Tomi, Intern',
    avatar: '🧢',
    text: 'So I built a bot that turns customer wins into short videos. It kind of went viral internally. Can we ship it? I go back to school in three weeks.',
    left: { label: 'Ship the intern bot', effects: { users: 10, team: 4, tech: -6 } },
    right: { label: 'Archive it politely', effects: { team: -4, tech: 4 } },
  },
  {
    id: 'meeting-audit',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'My engineers average 19 hours of meetings a week. I want to cancel every recurring meeting and let them re-add the ones they miss.',
    left: { label: 'Slash the meetings', effects: { team: 14, business: -4 } },
    right: { label: 'Alignment has a price', effects: { team: -6, business: 4 } },
  },
  {
    id: 'gdpr-list',
    speaker: 'Ravi, Legal',
    avatar: '⚖️',
    text: 'A third of the marketing list has no recorded consent. I recommend purging it before the audit. Marketing says that list is "the pipeline".',
    left: { label: 'Purge the list', effects: { business: -8, users: 4, tech: 4 } },
    right: { label: 'One more campaign first', effects: { business: 8, users: -6 } },
  },
  {
    id: 'oncall-pm',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'The team thinks product should feel the pager. One week per quarter, you carry it too. It would mean a lot. It would also mean 3am.',
    left: { label: 'Join the on-call rotation', effects: { team: 10, tech: 4, users: -4 } },
    right: { label: 'Product sleeps at night', effects: { team: -6, business: 4 } },
  },
  {
    id: 'beta-churn',
    speaker: 'Ana, Data',
    avatar: '📊',
    text: 'Beta users say the product changes under them every week. Power users love the pace; everyone else churns by day nine.',
    left: { label: 'Freeze the surface, polish', effects: { users: 8, tech: -4 } },
    right: { label: 'Keep the iteration pace', effects: { business: 4, users: -6 } },
  },
  {
    id: 'demo-vaporware',
    speaker: 'Jonas, Sales',
    avatar: '🤵',
    text: 'The demo environment shows an "AI insights" tab that is, generously, a Figma prototype. Prospects love it. Engineering does not know it exists.',
    left: { label: 'Let the demo ride', effects: { business: 10, team: -8, users: -4 } },
    right: { label: 'Kill the vaporware tab', effects: { business: -8, team: 6 } },
  },
  {
    id: 'board-okrs',
    speaker: 'The Board',
    avatar: '🏛️',
    text: 'The growth committee proposes next quarter’s headline OKR: triple weekly actives. The plan for how is, and we quote, "the product team’s job".',
    left: { label: 'Commit to 3x', effects: { business: 8, users: 4, team: -8 } },
    right: { label: 'Negotiate an honest target', effects: { business: -6, team: 6 } },
  },
  {
    id: 'android-crash',
    speaker: 'Priya, Support',
    avatar: '🎧',
    text: 'The new release crashes on 2% of Android devices — the cheap ones. That is 40,000 people. The fix is gnarly and the team is exhausted.',
    left: { label: 'Hotfix this weekend', effects: { tech: 8, users: 6, team: -10 } },
    right: { label: 'It ships Monday', effects: { users: -8, team: 4 } },
  },
  {
    id: 'open-api',
    speaker: 'Jonas, Sales',
    avatar: '🤵',
    text: 'Partners keep asking for a public API. It would open a whole channel — and freeze every internal interface we currently change weekly.',
    left: { label: 'Open the API', effects: { users: 8, business: 6, tech: -10 } },
    right: { label: 'Keep it internal', effects: { tech: 4, users: -4, business: -4 } },
  },
  {
    id: 'design-system-rebuild',
    speaker: 'Dele, Design',
    avatar: '🎨',
    text: 'We have four button styles and none of them are on purpose. A proper design system is six weeks and will make everything after it faster.',
    left: { label: 'Build the system', effects: { tech: 8, users: 4, business: -8 } },
    right: { label: 'Four buttons never hurt anyone', effects: { business: 4, tech: -6 } },
  },
  {
    id: 'churn-interviews',
    speaker: 'Ana, Data',
    avatar: '📊',
    text: 'I lined up interviews with twelve churned customers. It is a week of your calendar and it will hurt your feelings. The dashboard version is free.',
    left: { label: 'Run the interviews', effects: { users: 8, business: -4 } },
    right: { label: 'Trust the dashboard', effects: { business: 4, users: -6 } },
  },
  {
    id: 'hackathon-ask',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'The team wants a hackathon week. Last year’s produced our best feature and also three prototypes we are still apologizing for.',
    left: { label: 'Hackathon approved', effects: { team: 14, business: -6 } },
    right: { label: 'Roadmap needs us', effects: { team: -8, business: 6 } },
  },
  {
    id: 'seo-content-farm',
    speaker: 'Sam, Marketing',
    avatar: '📣',
    text: 'An agency will write 200 SEO articles about our category. The traffic projections are real. The articles will read like a robot ate a thesaurus.',
    left: { label: 'Sign the agency', effects: { users: 8, business: 4, tech: -4 } },
    right: { label: 'Protect the brand voice', effects: { users: -4, team: 4 } },
  },
  {
    id: 'legacy-webview',
    speaker: 'Priya, Support',
    avatar: '🎧',
    text: '6% of users are on an Android WebView from 2019. Supporting it costs the team a day per release. Dropping it orphans 120,000 people.',
    left: { label: 'Keep supporting them', effects: { users: 6, tech: -8 } },
    right: { label: 'Drop the old WebView', effects: { tech: 12, users: -8 } },
  },
  {
    id: 'bounty-report',
    speaker: 'Ravi, Legal',
    avatar: '⚖️',
    text: 'A security researcher reported an auth bypass, politely. They want a bounty we do not technically have a program for, and a patch within 30 days.',
    left: { label: 'Pay up, patch now', effects: { tech: 14, business: -6 } },
    right: { label: 'Patch quietly next sprint', effects: { business: 4, tech: -8, users: -4 } },
  },
  {
    id: 'public-roadmap',
    speaker: 'Sam, Marketing',
    avatar: '📣',
    text: 'Customers keep asking what is coming. A public roadmap builds trust — and hands our plans to the competitor who ships faster than we do.',
    left: { label: 'Publish the roadmap', effects: { users: 8, business: -4, team: -4 } },
    right: { label: 'Keep plans private', effects: { users: -4, team: 4 } },
  },
  {
    id: 'usage-pricing',
    speaker: 'Jonas, Sales',
    avatar: '🤵',
    text: 'Finance wants usage-based pricing. Ana says our metering is "an estimate wearing a suit". Customers on the old plan will fight the migration.',
    left: { label: 'Move to usage pricing', effects: { business: 8, users: -6, tech: -4 } },
    right: { label: 'Keep flat plans', effects: { users: 4, business: -6 } },
  },
  {
    id: 'founder-livestream',
    speaker: 'The CEO',
    avatar: '🧑‍💼',
    text: 'I want a weekly livestream where I demo unreleased features. Builds hype. Occasionally I will demo things that do not exist yet. Roll with it.',
    left: { label: 'Set up the stream', effects: { business: 6, team: -6, tech: -4 } },
    right: { label: 'Talk him down', effects: { business: -6, team: 4 } },
  },
  {
    id: 'sso-bill-due',
    speaker: 'Jonas, Sales',
    avatar: '🤵',
    text: 'Remember the SSO promise? The customer’s IT team just asked for a kickoff call. Legal says the contract has a penalty clause. Maya says "what SSO?"',
    requires: { flags: ['promised-sso'], week: { min: 6 } },
    left: { label: 'Pull two engineers onto SSO', effects: { business: 8, tech: -6, team: -6 } },
    right: { label: 'Slip the SSO date', effects: { business: -10, team: 4 } },
  },

  // ============================== arc: incident ==============================
  {
    id: 'incident-sev1',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'Payments were down for 41 minutes last night. We are stable now. I want a blameless postmortem this week; the CEO wants everyone back on the launch.',
    arc: 'incident',
    weight: 2,
    left: { label: 'Skip the postmortem', effects: { business: 6, tech: -6 }, setFlags: ['skipped-postmortem'] },
    right: { label: 'Run it blameless', effects: { business: -4, tech: 8, team: 4 }, setFlags: ['held-postmortem'] },
  },
  {
    id: 'incident-repeat',
    speaker: 'Priya, Support',
    avatar: '🎧',
    text: 'Payments are down again — same failure, worse timing. A customer’s CFO is live-tweeting it. Maya says one word: "postmortem".',
    arc: 'incident',
    requires: { flags: ['skipped-postmortem'], week: { min: 6 } },
    weight: 3,
    left: { label: 'All hands on the fire', effects: { tech: -12, business: -10, team: -6 } },
    right: { label: 'Statement first, fix second', effects: { business: -14, users: -8, tech: -6 } },
  },
  {
    id: 'incident-runbook',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'The postmortem found the real cause: a config path nobody owns. I want to fund the runbook and alerts properly so this class of outage dies here.',
    arc: 'incident',
    requires: { flags: ['held-postmortem'], week: { min: 6 } },
    weight: 3,
    left: { label: 'Fund the fix properly', effects: { tech: 14, business: -4 }, setFlags: ['arc:incident:resolved'] },
    right: { label: 'The postmortem was enough', effects: { business: 4, tech: -8 } },
  },

  // ============================ arc: big-customer ============================
  {
    id: 'big-customer-ask',
    speaker: 'Big-4 Customer',
    avatar: '🏢',
    text: 'We love the product. We will renew at double the seats — if you build a custom approval workflow only we will ever use. Our timeline is "soon".',
    arc: 'big-customer',
    weight: 2,
    left: { label: 'Promise the custom build', effects: { business: 10, tech: -6, team: -4 }, setFlags: ['promised-custom'] },
    right: { label: 'Hold the roadmap line', effects: { business: -8, team: 4 }, setFlags: ['held-roadmap'] },
  },
  {
    id: 'big-customer-escalation',
    speaker: 'The CEO',
    avatar: '🧑‍💼',
    text: 'The Big-4 account says their custom workflow is late and they are "evaluating alternatives". Their exec just emailed me directly. Fix this.',
    arc: 'big-customer',
    requires: { flags: ['promised-custom'], week: { min: 5 } },
    weight: 3,
    left: { label: 'Drop everything, deliver it', effects: { business: 8, team: -10, users: -6 } },
    right: { label: 'Renegotiate the scope', effects: { business: -10, team: 4 } },
  },
  {
    id: 'big-customer-renewal',
    speaker: 'Big-4 Customer',
    avatar: '🏢',
    text: 'Renewal call. You held your roadmap and, annoyingly, the product got better for it. Give us a real enterprise tier and we sign for two years.',
    arc: 'big-customer',
    requires: { flags: ['held-roadmap'], week: { min: 7 } },
    weight: 3,
    left: { label: 'Build the enterprise tier', effects: { business: 12, tech: -4 }, setFlags: ['arc:big-customer:resolved'] },
    right: { label: 'One-size-fits-all forever', effects: { business: -8, users: 4 } },
  },

  // ============================== arc: burnout ==============================
  {
    id: 'burnout-crunch',
    speaker: 'The CEO',
    avatar: '🧑‍💼',
    text: 'The launch window is real: our biggest partner announces in five weeks. I am asking the team for evenings and weekends until then. Back me up.',
    arc: 'burnout',
    weight: 2,
    left: { label: 'Call the crunch', effects: { business: 8, team: -10 }, setFlags: ['crunch-called'] },
    right: { label: 'Refuse the crunch', effects: { business: -8, team: 10 }, setFlags: ['crunch-refused'] },
  },
  {
    id: 'burnout-resignation',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'Sofia — the engineer who understands billing — just told me she is interviewing. She says the crunch was the moment it stopped being worth it.',
    arc: 'burnout',
    requires: { flags: ['crunch-called'], week: { min: 5 } },
    weight: 3,
    left: { label: 'Counter-offer and apologize', effects: { team: 12, business: -8 } },
    right: { label: 'Nobody is irreplaceable', effects: { team: -12, tech: -8 } },
  },
  {
    id: 'burnout-reset',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'The crunch got us the launch. It also got us three resignation-adjacent 1:1s. I want a no-meetings recovery sprint: bugs, naps, and nothing heroic.',
    arc: 'burnout',
    requires: { flags: ['crunch-called'], week: { min: 7 } },
    weight: 3,
    left: { label: 'Grant the recovery sprint', effects: { team: 14, business: -6 }, setFlags: ['arc:burnout:resolved'] },
    right: { label: 'Momentum first', effects: { business: 6, team: -10 } },
  },

  // =========================== arc: launch-gamble ===========================
  {
    id: 'launch-gamble-date',
    speaker: 'Sam, Marketing',
    avatar: '📣',
    text: 'I got us a keynote slot at the industry conference — in three weeks. Maya says the feature needs five. A launch there is worth six months of ads.',
    arc: 'launch-gamble',
    weight: 2,
    left: { label: 'Ship for the keynote', effects: { users: 10, business: 6, tech: -8 }, setFlags: ['shipped-early'] },
    right: { label: 'Slip past the keynote', effects: { business: -8, tech: 6 }, setFlags: ['slipped-launch'] },
  },
  {
    id: 'launch-gamble-press',
    speaker: 'Sam, Marketing',
    avatar: '📣',
    text: 'The keynote demo froze on stage. The write-ups are "ambitious but shaky". Signups spiked anyway — and so did one-star reviews mentioning bugs.',
    arc: 'launch-gamble',
    requires: { flags: ['shipped-early'], week: { min: 4 } },
    weight: 3,
    left: { label: 'Own it publicly, fix fast', effects: { users: 6, tech: -6, team: -4 } },
    right: { label: 'Ride the signup spike', effects: { users: -8, business: 6, tech: -6 } },
  },
  {
    id: 'launch-gamble-stabilize',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'The early launch left a crater: flaky sync, angry reviews, a bug tail we keep not paying down. Two weeks of stabilization makes it a real feature.',
    arc: 'launch-gamble',
    requires: { flags: ['shipped-early'], week: { min: 6 } },
    weight: 3,
    left: { label: 'Freeze and stabilize', effects: { tech: 12, users: 6, business: -6 }, setFlags: ['arc:launch-gamble:resolved'] },
    right: { label: 'The crater is character', effects: { users: -8, tech: -8 } },
  },

  // ============================ overshoot: users =============================
  {
    id: 'viral-spike',
    speaker: 'Priya, Support',
    avatar: '🎧',
    text: 'We are on the front page of everything. Sign-ups are 40x. The support queue is nine hours deep and the database is sweating. Enjoying the moment?',
    overshoot: 'users',
    requires: { meter: { users: { min: 85 } } },
    left: { label: 'Throttle sign-ups', effects: { users: -12, tech: -4, team: -6 } },
    right: { label: 'Ride the wave', effects: { users: -6, tech: -14, team: -10 } },
  },
  {
    id: 'influencer-flood',
    speaker: 'Sam, Marketing',
    avatar: '📣',
    text: 'An influencer with eight million followers made us "the app of the week". Half the new users are here for a feature we do not actually have.',
    overshoot: 'users',
    requires: { meter: { users: { min: 85 } } },
    left: { label: 'Build what they came for', effects: { users: -4, tech: -10, team: -8 } },
    right: { label: 'Let the tourists churn', effects: { users: -14, business: -6, team: -4 } },
  },

  // =========================== overshoot: business ===========================
  {
    id: 'monetization-squeeze',
    speaker: 'The Board',
    avatar: '🏛️',
    text: 'Revenue is beating plan. The board wants to "capture the value": paywall two free features and add seats-based billing. This quarter.',
    overshoot: 'business',
    requires: { meter: { business: { min: 85 } } },
    left: { label: 'Paywall the features', effects: { business: -4, users: -14, team: -6 } },
    right: { label: 'Defend the free tier', effects: { business: -12, users: -4, team: -4 } },
  },
  {
    id: 'growth-at-all-costs',
    speaker: 'The CEO',
    avatar: '🧑‍💼',
    text: 'With numbers like these we raise a monster round. I already told two investors about features we have not started. The deck writes checks now.',
    overshoot: 'business',
    requires: { meter: { business: { min: 85 } } },
    left: { label: 'Chase the deck’s promises', effects: { business: -6, tech: -12, team: -8 } },
    right: { label: 'Reset investor expectations', effects: { business: -14, users: -4, team: -4 } },
  },

  // ============================= overshoot: team =============================
  {
    id: 'comfort-culture',
    speaker: 'The CEO',
    avatar: '🧑‍💼',
    text: 'Morale is spectacular. Velocity is… decorative. Three retro action items this month were about snacks. The board is asking what everyone does.',
    overshoot: 'team',
    requires: { meter: { team: { min: 85 } } },
    left: { label: 'Tighten the goals', effects: { team: -12, business: -4, users: -4 } },
    right: { label: 'Happy teams ship, eventually', effects: { team: -6, business: -12, tech: -6 } },
  },
  {
    id: 'perpetual-hack-week',
    speaker: 'Ana, Data',
    avatar: '📊',
    text: 'The team has shipped four internal tools, a coffee bot, and zero roadmap items this month. Everyone is thriving. The roadmap is not.',
    overshoot: 'team',
    requires: { meter: { team: { min: 85 } } },
    left: { label: 'Back to the roadmap', effects: { team: -10, business: -4, users: -6 } },
    right: { label: 'The bot stays', effects: { team: -4, business: -10, users: -8 } },
  },

  // ============================= overshoot: tech =============================
  {
    id: 'gold-plating',
    speaker: 'The CEO',
    avatar: '🧑‍💼',
    text: 'Engineering rewrote the sync engine for the third time. It is now, I am told, "beautiful". Customers are asking when we will ship literally anything.',
    overshoot: 'tech',
    requires: { meter: { tech: { min: 85 } } },
    left: { label: 'Feature mode, effective today', effects: { tech: -12, team: -6, users: -4 } },
    right: { label: 'Beauty is a moat', effects: { tech: -6, business: -12, users: -8 } },
  },
  {
    id: 'replatform-dream',
    speaker: 'Maya, Eng Lead',
    avatar: '👩‍💻',
    text: 'The platform is so healthy the team wants to replatform onto the new hotness "while things are quiet". Sales just heard the word "freeze".',
    overshoot: 'tech',
    requires: { meter: { tech: { min: 85 } } },
    left: { label: 'Approve the replatform', effects: { tech: -8, business: -12, users: -6 } },
    right: { label: 'Quiet is for shipping', effects: { tech: -10, team: -8, business: -4 } },
  },
];
